function renderMonitorPage(nonce) {
    return `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MiniZeus 서버 상태</title>
<style>body{font:16px/1.6 system-ui;max-width:1100px;margin:24px auto;padding:20px;background:#101a24;color:#e5edf4}a{color:#b8d5ed}h1{font-size:25px}h2{font-size:19px}.scroll{overflow:auto}table{border-collapse:collapse;min-width:650px;width:100%}th,td{text-align:left;padding:9px;border-bottom:1px solid #405264}.panel{padding:14px;background:#203343;margin:14px 0;white-space:pre-line}.warning{color:#ffd2a1}.error{color:#ff9d9d}button{font:inherit;padding:8px 16px}svg{width:100%;height:160px;background:#1c2b37}small{color:#b7c8d7}#events{font-size:14px}#history-note{font-size:14px}</style>
<a href="/admin">관리자 홈</a> · <a href="/admin/admission">입장 정원</a><h1>서버 다운·오류·증가 추세</h1>
<p id="connection" class="panel">상태 조회 중</p><button id="refresh">지금 새로고침</button><small> 30초마다 화면 갱신 · 서버 관측 1분 간격 · 상태 확인 전용</small>
<p id="summary" class="panel"></p><p id="rates" class="panel"></p>
<h2>다른 서버에서 확인한 응답 상태</h2><div class="scroll"><table><thead><tr><th>서버</th><th>상태</th><th>응답 시간</th><th>서버 오류/요청</th><th>마지막 확인</th></tr></thead><tbody id="peers"></tbody></table></div>
<small>연속 3회 응답 실패는 접근 불가로 표시합니다. 같은 Railway 플랫폼 안의 교차 감시여서 플랫폼 전체 장애는 별도 외부 감시가 필요합니다.</small>
<h2>최근 24시간 HTTP 서버 오류율</h2><svg id="chart" viewBox="0 0 900 160" preserveAspectRatio="none" role="img" aria-label="관측된 분별 HTTP 서버 오류율"></svg><p id="history-note"></p>
<details><summary>분별 요청·오류 기록</summary><div class="scroll"><table><thead><tr><th>시각</th><th>요청</th><th>서버 오류</th><th>오류율</th><th>만석·점검 등</th><th>비정상 종료/전체 종료</th></tr></thead><tbody id="history"></tbody></table></div></details>
<h2>최근 변화 · 현재 프로세스</h2><ul id="events"></ul><small>요청 본문·플레이어 정보는 저장하지 않습니다. HTTP 5xx, 백그라운드 오류, WebSocket 비정상 종료를 구분합니다. 만석/점검 503과 클라이언트 4xx는 서버 오류율에 포함하지 않습니다. 비정상 종료에는 이용자 네트워크 단절도 포함됩니다.</small>
<script nonce="${nonce}">
const el=id=>document.getElementById(id), pct=n=>n==null?'활동 없음':(n*100).toFixed(2)+'%', time=t=>t?new Date(t).toLocaleString():'관측 대기';
const labels={ok:'응답 정상',pending:'관측 대기',checking_failure:'응답 실패 · 재확인 중',unreachable:'접근 불가',degraded:'응답 있음 · 오류 관측',stale:'관측 오래됨',error:'오류',not_configured:'DB 미사용',warming_up:'관측 시작 후 10분 미만',insufficient_samples:'표본 부족',rising:'오류율 상승',stable:'상승 신호 없음',database_unavailable:'DB 연결 이상',errors_observed:'오류 관측'};
function cellRow(values){const tr=document.createElement('tr');for(const value of values){const td=document.createElement('td');td.textContent=value;tr.append(td)}return tr}
function draw(data){const s=data.snapshot,c=s.comparison;el('connection').className='panel';el('connection').textContent='조회 성공 · '+time(s.observedAt)+' · '+s.poolId;el('summary').textContent='DB: '+(labels[s.database.status]||s.database.status)+' · 확인 '+time(s.database.checkedAt)+'\\n집계 저장: '+s.storageStatus+' · 프로세스 시작 '+time(s.startedAt);el('summary').className='panel '+(s.status==='database_unavailable'?'error':'');el('rates').textContent='최근 완료된 5분: '+c.current.failures+' / '+c.current.requests+'건 ('+pct(c.currentRate)+')\\n직전 5분: '+c.previous.failures+' / '+c.previous.requests+'건 ('+pct(c.previousRate)+') · '+(labels[c.trend]||c.trend)+'\\n현재 진행 중 1분: 서버 오류 '+s.currentMinute.failures+'건 · 백그라운드 오류 '+s.currentMinute.backgroundErrors+'건\\n최근 5분 비정상 연결 종료 '+c.current.wsAbnormal+' / '+c.current.wsClosed+'건 · 백그라운드 오류 '+c.current.backgroundErrors+'건\\n연결 인증 처리 실패 '+c.current.wsUpgradeFailures+' / '+c.current.wsUpgradeRequests+'건 (인증 거절 '+c.current.wsUpgradeRejected+'건은 별도)';el('rates').className='panel '+(c.trend==='rising'?'error':c.current.failures?'warning':'');
el('peers').replaceChildren(...s.peers.map(p=>cellRow([p.name,labels[p.state]||p.state,p.latencyMs==null?'—':p.latencyMs+'ms',p.runtime?p.runtime.http5xx+' / '+p.runtime.requests:'상세 집계 없음',time(p.checkedAt)])));
const rows=data.history;el('history').replaceChildren(...rows.slice().reverse().map(r=>cellRow([time(r.minute),r.requests,r.failures,pct(r.requests?r.failures/r.requests:null),r.expectedRejections,r.wsAbnormal+' / '+r.wsClosed])));
el('history-note').textContent=rows.length+'분의 기록 · 요청 없는 분/미관측 구간은 오류율 선을 잇지 않습니다. 세로축 0~100%. 재시작 전 기록은 DB가 정상일 때 조회합니다.';
el('chart').replaceChildren();const end=Date.now(),start=end-24*3600000;let points=[],last=null;function flush(){if(points.length){const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.setAttribute('points',points.join(' '));line.setAttribute('stroke','#ffa787');line.setAttribute('stroke-width','2');line.setAttribute('fill','none');el('chart').append(line)}points=[]}
for(const r of rows){if(!r.requests){flush();last=null;continue}if(last!==null&&r.minute-last>90000)flush();const x=(r.minute-start)/(end-start)*900,y=150-r.failures/r.requests*140;points.push(x+','+y);const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',x);dot.setAttribute('cy',y);dot.setAttribute('r','2');dot.setAttribute('fill','#ffa787');el('chart').append(dot);last=r.minute}flush();
el('events').replaceChildren(...s.events.map(e=>{const li=document.createElement('li');li.textContent=time(e.at)+' · '+e.target+' · '+e.kind;return li}));}
let busy=false;async function refresh(){if(busy)return;busy=true;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{const response=await fetch('/admin/api/monitor',{cache:'no-store',signal:controller.signal});if(!response.ok)throw Error('HTTP '+response.status);draw(await response.json())}catch(error){el('connection').className='panel error';el('connection').textContent='이 관리자 서버의 상태를 가져올 수 없습니다. 아래 값은 이전 조회 결과일 수 있습니다. '+time(Date.now())}finally{clearTimeout(timer);busy=false}}
el('refresh').onclick=refresh;refresh();setInterval(refresh,30000);
</script></html>`;
}
module.exports = { renderMonitorPage };
